### ISSUE TITLE
URLs failing the validation

### ISSUE THREAD

**Issue by libremente** [alranel/go-vcsurl#2]
Right now the following URLs are failing the validation (I believe the `IsRepo` function returns `false`). 
*  https://git.libreoffice.org/core

Let me know if you need further info @alranel

**Comment by libremente** [comment]
https://gerrit.libreoffice.org/plugins/gitiles/core

**Comment by deneb-alpha** [comment]
hello. do you have any ETA and/or updates for this issue? is there something that we can do?
